import { Tea } from "./types";

export const teas: Tea[] = [
  {
    id: "matcha",
    name: "Matcha",
    emoji: "🍵",
    category: "Green Tea",
    caffeine: "high",
    flavors: ["earthy", "fresh"],
    goals: ["energy", "wellness"],
    times: ["morning"],
    steepTemp: "175°F (80°C)",
    steepTime: "Whisk 15–30 seconds",
    description:
      "A vibrant, stone-ground green tea that delivers steady, jitter-free energy and a wave of antioxidants.",
    ritual:
      "Sift a teaspoon into your bowl, add a splash of hot water, and whisk briskly in a zig-zag until frothy.",
  },
  {
    id: "sencha",
    name: "Sencha",
    emoji: "🌿",
    category: "Green Tea",
    caffeine: "medium",
    flavors: ["fresh", "earthy"],
    goals: ["energy", "wellness"],
    times: ["morning", "afternoon"],
    steepTemp: "175°F (80°C)",
    steepTime: "2 minutes",
    description:
      "A grassy, vegetal green tea with a clean finish — bright enough to wake you up without overwhelming you.",
    ritual:
      "Let just-boiled water rest for a minute before pouring, so the delicate leaves don't turn bitter.",
  },
  {
    id: "dragonwell",
    name: "Dragonwell",
    emoji: "🍃",
    category: "Green Tea",
    caffeine: "medium",
    flavors: ["earthy", "fresh"],
    goals: ["energy", "wellness"],
    times: ["morning", "afternoon"],
    steepTemp: "175°F (80°C)",
    steepTime: "3 minutes",
    description:
      "A pan-fired Chinese green tea with a toasty, chestnut-like sweetness and a calm, focused lift.",
    ritual:
      "Use a glass vessel if you can — watching the flat leaves unfurl is half the pleasure.",
  },
  {
    id: "assam",
    name: "Assam Black",
    emoji: "☕",
    category: "Black Tea",
    caffeine: "high",
    flavors: ["earthy", "spiced"],
    goals: ["energy"],
    times: ["morning"],
    steepTemp: "212°F (100°C)",
    steepTime: "4 minutes",
    description:
      "A bold, malty black tea built for mornings that need a real push out the door.",
    ritual:
      "Steep it strong and add a splash of milk if you like — it can easily carry the weight.",
  },
  {
    id: "earl-grey",
    name: "Earl Grey",
    emoji: "🫖",
    category: "Black Tea",
    caffeine: "medium",
    flavors: ["floral", "fruity"],
    goals: ["energy", "relax"],
    times: ["morning", "afternoon"],
    steepTemp: "200°F (93°C)",
    steepTime: "3–4 minutes",
    description:
      "Classic black tea scented with bergamot — bright citrus notes over a smooth, brisk base.",
    ritual:
      "Cover your cup while it steeps to trap the citrus aromatics before your first sip.",
  },
  {
    id: "chai",
    name: "Masala Chai",
    emoji: "🫚",
    category: "Spiced Black Tea",
    caffeine: "medium",
    flavors: ["spiced", "earthy"],
    goals: ["energy", "relax"],
    times: ["morning", "afternoon"],
    steepTemp: "212°F (100°C)",
    steepTime: "5 minutes, simmered",
    description:
      "Black tea simmered with warming spices like cardamom, ginger, and cinnamon — cozy and grounding.",
    ritual:
      "Simmer the spices in water first, then add the tea leaves and a milk of your choice.",
  },
  {
    id: "white-peony",
    name: "White Peony",
    emoji: "🌸",
    category: "White Tea",
    caffeine: "low",
    flavors: ["floral", "fresh"],
    goals: ["relax", "wellness"],
    times: ["afternoon"],
    steepTemp: "185°F (85°C)",
    steepTime: "3–4 minutes",
    description:
      "A delicate, subtly sweet white tea with soft floral notes — gentle on the senses and the stomach.",
    ritual: "Use more leaf than you think — white tea is forgiving and loves a generous steep.",
  },
  {
    id: "oolong",
    name: "Tie Guan Yin Oolong",
    emoji: "🍂",
    category: "Oolong",
    caffeine: "medium",
    flavors: ["floral", "earthy"],
    goals: ["wellness", "relax"],
    times: ["afternoon"],
    steepTemp: "195°F (90°C)",
    steepTime: "1 minute, multiple infusions",
    description:
      "A partially oxidized tea with an orchid-like aroma and a smooth, evolving flavor across infusions.",
    ritual:
      "Re-steep the same leaves 3–4 times, adding a few seconds to each infusion for a slow afternoon ritual.",
  },
  {
    id: "puerh",
    name: "Pu-erh",
    emoji: "🟤",
    category: "Fermented Tea",
    caffeine: "medium",
    flavors: ["earthy"],
    goals: ["digestion", "wellness"],
    times: ["afternoon", "evening"],
    steepTemp: "212°F (100°C)",
    steepTime: "30 seconds rinse, then 2–3 minutes",
    description:
      "A dark, earthy fermented tea traditionally sipped after meals to settle and support digestion.",
    ritual:
      "Rinse the leaves briefly with hot water first, then discard that rinse before your real steep.",
  },
  {
    id: "peppermint",
    name: "Peppermint",
    emoji: "🌱",
    category: "Herbal",
    caffeine: "none",
    flavors: ["fresh"],
    goals: ["digestion", "relax"],
    times: ["afternoon", "evening"],
    steepTemp: "212°F (100°C)",
    steepTime: "5–7 minutes",
    description:
      "A cooling, caffeine-free herbal infusion known for soothing the stomach and clearing the mind.",
    ritual: "Crush a leaf between your fingers before steeping to release extra aroma.",
  },
  {
    id: "ginger",
    name: "Ginger Root",
    emoji: "🫙",
    category: "Herbal",
    caffeine: "none",
    flavors: ["spiced"],
    goals: ["digestion", "wellness"],
    times: ["morning", "afternoon"],
    steepTemp: "212°F (100°C)",
    steepTime: "8–10 minutes",
    description:
      "A warming, spicy-sweet root infusion that supports digestion and wakes up the senses without caffeine.",
    ritual: "Add a slice of fresh ginger and a squeeze of lemon for extra brightness.",
  },
  {
    id: "chamomile",
    name: "Chamomile",
    emoji: "🌼",
    category: "Herbal",
    caffeine: "none",
    flavors: ["floral"],
    goals: ["sleep", "relax"],
    times: ["evening"],
    steepTemp: "212°F (100°C)",
    steepTime: "5 minutes",
    description:
      "A honey-sweet, apple-like floral infusion that's practically synonymous with winding down.",
    ritual: "Steep with the lid on to keep the calming aromatics from escaping.",
  },
  {
    id: "lavender",
    name: "Lavender Herbal",
    emoji: "💜",
    category: "Herbal",
    caffeine: "none",
    flavors: ["floral"],
    goals: ["sleep", "relax"],
    times: ["evening"],
    steepTemp: "212°F (100°C)",
    steepTime: "5 minutes",
    description:
      "A soft, perfumed infusion that pairs beautifully with chamomile or on its own before bed.",
    ritual: "Dim the lights and sip slowly — this one rewards a slow, unhurried pace.",
  },
  {
    id: "rooibos",
    name: "Rooibos",
    emoji: "🟠",
    category: "Herbal",
    caffeine: "none",
    flavors: ["earthy", "fruity"],
    goals: ["relax", "wellness"],
    times: ["afternoon", "evening"],
    steepTemp: "212°F (100°C)",
    steepTime: "5–7 minutes",
    description:
      "A naturally sweet, caffeine-free red bush tea from South Africa with a smooth, woody warmth.",
    ritual: "It's nearly impossible to over-steep — let it sit as long as you like.",
  },
  {
    id: "hibiscus",
    name: "Hibiscus",
    emoji: "🌺",
    category: "Herbal",
    caffeine: "none",
    flavors: ["fruity"],
    goals: ["wellness", "relax"],
    times: ["afternoon", "evening"],
    steepTemp: "212°F (100°C)",
    steepTime: "5 minutes",
    description:
      "A tart, ruby-red infusion bursting with fruity brightness — refreshing hot or over ice.",
    ritual: "Sweeten lightly with honey to balance the tartness if you'd like.",
  },
  {
    id: "lemon-balm",
    name: "Lemon Balm",
    emoji: "🍋",
    category: "Herbal",
    caffeine: "none",
    flavors: ["fresh", "fruity"],
    goals: ["relax", "sleep"],
    times: ["evening"],
    steepTemp: "212°F (100°C)",
    steepTime: "6 minutes",
    description:
      "A gently lemony herbal infusion long used to quiet a busy mind before rest.",
    ritual: "Pair with a few mint leaves for a brighter, more fragrant cup.",
  },
];
